[server]
enableStaticServing = true

[theme]
primaryColor = "#c8102e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#212529"
font = "sans serif"

[theme.sidebar]
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"

